CREATE DATABASE built2GSD_SQL_DB;

CREATE TABLE CUSTOMERS(
 ID INT NOT NULL,
 FIRSTNAME VARCHAR (30) NOT NULL,
 MIDDLENAME VARCHAR (30) NOT NULL,
 LASTNAME VARCHAR (30) NOT NULL,
 AGE INT NOT NULL,
 ADDRESS CHAR (25) ,
 SALARY DECIMAL (18, 2),
 PRIMARY KEY (ID)
);